### ISSUE TITLE
how to avoid version conflicts in feedstocks that depend on libitk?

### ISSUE THREAD

**Issue by KrisThielemans** [conda-forge/libitk-feedstock#75]
### Comment:

Our [STIR feedstock](https://github.com/conda-forge/stir-feedstock/) uses `libitk` in our recipe as follows:
```
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - libitk-devel
    - libitk <5.2  # [win]
    - libitk  # [not win]
  run:
    - {{ pin_compatible('libitk', min_pin='x.x', max_pin='x.x') }}
```
(cutting out non-ITK stuff). The `pin_compatible` line was put in by  @carterbox in an attempt to fix the problem that the tests or actual downloaded package uses a different version of ITK than what was used to build, resulting in shared-libraries not found, but it is still happening, see
https://github.com/conda-forge/stir-feedstock/issues/34

Any suggestions how we should fix this properly?
